# Schema for the configuration files of the DrupalEasy Repositories module.
drupaleasy_repositories.settings:
  type: config_object
  label: 'DrupalEasy Repositories settings'
  mapping:
    repositories:
      type: sequence
      label: 'Repositories'
      sequence:
        type: string
